version: '3.8'

services:
  api:
    build: .
    container_name: log-triager-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - VECTOR_DB_URL=http://chromadb:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL_NAME=gpt-4o

    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma:0.5.0
    container_name: log-triager-chromadb
    ports:
      - "8001:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    restart: unless-stopped

volumes:
  chromadb_data:
